name: Deploy wordaday-backend

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t matt1128jr/wordaday-backend .

      - name: Publish Image to Docker Hub
        run: docker push matt1128jr/wordaday-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull matt1128jr/wordaday-backend:latest

      - name: Delete old container
        run: docker rm -f wordaday-backend-container || true  # This ensures it doesn't fail if the container doesn't exist

      - name: Run Docker Container
        run: |
          docker run -d -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
          --name wordaday-backend-container \
          -e MONGO_URI='${{ secrets.MONGO_URI }}' \
          -e SECRET='${{ secrets.SECRET }}' \
          -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' \
          matt1128jr/wordaday-backend
